server:
  port: 8778
spring:
  application:
    name: spring-cloud-consumer

eureka:
  client:
    service-url:
      defaultZone: http://114.115.131.208:8761/eureka/
    fetch-registry: true
    # register-with-eureka: false
